"""comment1

Revision ID: 10aae30482c
Revises: 267c952274e
Create Date: 2015-01-04 13:03:57.346150

"""

# revision identifiers, used by Alembic.
revision = '10aae30482c'
down_revision = '267c952274e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
