"""mailconfirm

Revision ID: 203db12bbc6
Revises: 56dc614e537
Create Date: 2014-12-26 23:18:34.353023

"""

# revision identifiers, used by Alembic.
revision = '203db12bbc6'
down_revision = '56dc614e537'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
