"""initial migration

Revision ID: 2a65ca7a00a
Revises: None
Create Date: 2014-12-26 21:49:11.095830

"""

# revision identifiers, used by Alembic.
revision = '2a65ca7a00a'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    ### end Alembic commands ###
