"""post tile

Revision ID: 335fa7983cd
Revises: 10aae30482c
Create Date: 2015-01-09 12:58:28.287471

"""

# revision identifiers, used by Alembic.
revision = '335fa7983cd'
down_revision = '10aae30482c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
