"""admin permission

Revision ID: 4941da60156
Revises: e620352275
Create Date: 2014-12-30 13:44:03.335872

"""

# revision identifiers, used by Alembic.
revision = '4941da60156'
down_revision = 'e620352275'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
