"""changepasswordform

Revision ID: 56dc614e537
Revises: 2a65ca7a00a
Create Date: 2014-12-26 22:35:38.591843

"""

# revision identifiers, used by Alembic.
revision = '56dc614e537'
down_revision = '2a65ca7a00a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
