"""avatar_hash

Revision ID: 5a7f4bcfbfb
Revises: 49cd04df1da
Create Date: 2014-12-29 22:11:49.545592

"""

# revision identifiers, used by Alembic.
revision = '5a7f4bcfbfb'
down_revision = '49cd04df1da'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
